In [7]:
for i in range(4):
    for j in range(4):
        if i+j<=2:
            print(" ",end=" ")
        if i+j>=3:
            print("*",end=" ")
    print( )
            

      * 
    * * 
  * * * 
* * * * 


In [10]:
name=input("enter the name")
for i in range(len(name)):
    for j in range(i+1):
        print(name[i],end=' ')
    print()
        


enter the namevirat
v 
i i 
r r r 
a a a a 
t t t t t 


In [2]:
rec={}
n=int(input("enter the number of students"))
i=1
while i<=n:
    name=input("enter the student name")
    marks=input("enter % marks of students")
    rec[name]=marks
    i+=1
print("name of student","\t","% of marks")
for x in rec:
    print("\t",x,"\t\t",rec[x])

enter the number of students2
enter the student namesdf
enter % marks of students23
enter the student namedfsd
enter % marks of students345
name of student 	 % of marks
	 sdf 		 23
	 dfsd 		 345


In [4]:
d={1:"shobhith",2:"sharan",3:"sandesh"}

In [5]:
d

{1: 'shobhith', 2: 'sharan', 3: 'sandesh'}

In [7]:
d.clear()

In [8]:
d

{}

In [9]:
print("sho")

sho


In [10]:
d={1:"shobhith",2:"sharan",3:"sandesh"}
len(d)

3

In [11]:
word=input("enter any word")
d={}
for x in word:
    d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occure",v,"items")
    

enter any wordhhhheeelllooo
h occure 4 items
e occure 3 items
l occure 3 items
o occure 3 items


In [15]:
word=input("enter the string")
d={}
vowels={'a','e','i','o','u'}
for x in word:
    if x in vowels:
        d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occure",v,"items")
    

enter the stringhello
e occure 1 items
o occure 1 items


In [17]:
squares={x:x*x for x in range(1,6)}
print(squares)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [19]:
n=[1,2,3,4,5,5,5,5]
print(n.count(5))

4


In [20]:
print(n.index(5))

4


In [21]:
n=[1,2,3,4]
n.insert(1,123)
print(n)

[1, 123, 2, 3, 4]


In [23]:
list1=[1,2,3,"hello"]
list2=[4,5,6,"how"]
list1.extend(list2)
print(list1)

[1, 2, 3, 'hello', 4, 5, 6, 'how']


### remove from list

In [24]:
n=[1,2,3,4]
n.remove(1)
print(n)

[2, 3, 4]


### pop from the list

In [25]:
n=[1,2,3,4]
n.pop()
print(n)

[1, 2, 3]


In [26]:
n=[1,2,3,4]
n.reverse()
print(n)

[4, 3, 2, 1]


In [29]:
n=["shobhith","prathyush marle","reevan","shreyan madikeri"]
n.sort()
print(n)

['prathyush marle', 'reevan', 'shobhith', 'shreyan madikeri']


In [30]:
n=["shobhith","prathyush marle","reevan",2,"shreyan madikeri",1]
n.sort()
print(n)

TypeError: '<' not supported between instances of 'int' and 'str'

In [31]:
n=["shobhith","prathyush marle","reevan","shreyan madikeri"]
n.sort(reverse=True)
print(n)

['shreyan madikeri', 'shobhith', 'reevan', 'prathyush marle']


In [32]:
x=[10,20,30,40]
y=x[:]
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


### copy by reference

In [34]:
x=[10,20,30,40]
y=x
y[1]=777
print(x)
print(y)

[10, 777, 30, 40]
[10, 777, 30, 40]


### copy by value

In [35]:
x=[10,20,30,40]
y=x.copy()
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [36]:
a=[10,20,30]
b=[40,50,60]
c=a+b
print(c)

[10, 20, 30, 40, 50, 60]


In [37]:
a=[10,20,30]
b=[40,50,60]
c=x*3
print(c)

[10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40]


In [38]:
x=['nitte','mangalore','mite']
y=['nitte','mangalore','mite']
x==y
x!=y
z=['nitte','mangalore','mite']
x==z

True

In [39]:
m=[10,20,30,40,[50,60,70]]
m[3]
m[4][1]
m.clear()

In [40]:
m

[]

In [41]:
n=[1,2,3,4]
print(4 in n)

True


In [42]:
s=[2**x for x in range(16)]
print(s)

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768]


In [43]:
words=["mite","mysoore","shobhith"]
l=[w[0] for w in words]
print(l)

['m', 'm', 's']


In [46]:
def prime(n):
    flag=0
    for i in range(2,n):
        if n%i==0:
            flag=1
        if flag==1:
            return 'Not a Prime'
        else:
            return 'Prime'

prime(4)

'Not a Prime'

In [47]:
def times2(var):
    return var*2
seq=[1,2,3,4,5]
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [48]:
seq=[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))

[2, 4, 6, 8, 10]

In [49]:
seq=[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))
list(filter(lambda item:item%2==0,seq))

[2, 4]

In [1]:
import numpy as np


In [2]:
np

<module 'numpy' from 'E:\\anaconda\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
import pandas as pd


In [5]:
pd

<module 'pandas' from 'E:\\anaconda\\lib\\site-packages\\pandas\\__init__.py'>

In [6]:
import numpy as np
my_list=[1,2,3]
my_list
np.array(my_list)

array([1, 2, 3])

In [8]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
my_mat
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(2)


array([0.6450091, 0.8914782])

In [24]:
np.random.rand(5,5)

array([[0.12243028, 0.15605517, 0.83550124, 0.75044034, 0.17923538],
       [0.50235151, 0.10626405, 0.13632569, 0.00439431, 0.45683351],
       [0.51761978, 0.59203703, 0.09008783, 0.96813181, 0.89153575],
       [0.64117072, 0.40913748, 0.44125382, 0.14101451, 0.74752484],
       [0.12104191, 0.61215612, 0.46347973, 0.32097852, 0.89426435]])

In [26]:
np.random.randn(5,5)

array([[-0.38943961, -0.03273703,  1.09646914, -0.56457333,  1.079575  ],
       [ 0.94464616, -1.29703081,  1.15104132,  0.64636967,  0.28596223],
       [-0.73511419,  1.34968955, -0.26595558,  0.22795852, -0.58116565],
       [-0.34558767, -0.22327645,  0.5053424 ,  1.41101347,  0.50003554],
       [-0.350079  , -0.31352456, -0.88939799, -0.58750683, -0.36225809]])

In [28]:
ar=np.random.randint(1,100,10)
print(ar)

[40 41 10 61 27 81 68 53 55  6]


In [30]:
runarr=np.random.randint(0,50,10)
print(runarr)

[49  4 49 31 41 40 21 35  8 23]


In [40]:
arr=np.arange(25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
runarr.max()

49

In [42]:
runarr.argmax()

0

In [44]:
arr.shape

(25,)

In [45]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [46]:
arr.reshape(1,25).shape

(1, 25)

In [48]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [49]:
arr.reshape(25,1).shape

(25, 1)

In [50]:
arr.dtype

dtype('int32')

In [52]:
arr=np.arange(0,10)

In [53]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [54]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [55]:
arr/arr

E:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [56]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
1/arr

E:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [58]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [59]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [61]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [62]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [63]:
np.log(arr)

E:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [64]:
np.log(arr)

E:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [66]:
arr=np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [67]:
arr[8]

8

In [68]:
arr[1:5]

array([1, 2, 3, 4])

In [69]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [72]:
arr[0:5]=100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [73]:
arr>4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [74]:
arr>100

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [75]:
arr[arr>4]

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [78]:
arr[arr>5]

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

### create an array that consist of 12 zeros .
create an array that consist of 15 ones.create an array that consist of 10 5.create an array that consist of even numbers from 10 to 80 generate the 3*3 matrix consisting of valueand 25 random numbers following bell curve which is positive and negative integer

In [79]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [80]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
my_lis=[5,5,5,5,5,5,5,5,5,5]
my_lis
np.array(my_lis)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])